# ==============================
# DEV environment  (namespace: ultimate-web-stack-dev, deploys from main)
# ==============================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ultimate-web-stack-dev

labels:
  - pairs:
      app.kubernetes.io/environment: dev
    includeSelectors: false

resources:
  - ../base
  - ingress.yaml

images:
  - name: mainpi.local:5000/ultimate-web-stack/web
    newTag: dev

patches:
  - path: patch-web-env.yaml
    target:
      kind: Deployment
      name: web
