# ==============================
# PROD environment  (namespace: ultimate-web-stack, deploys from tags)
# ==============================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ultimate-web-stack

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: false

resources:
  - ../base

images:
  - name: mainpi.local:5000/ultimate-web-stack/backend
    newTag: prod
  - name: mainpi.local:5000/ultimate-web-stack/frontend
    newTag: prod

patches:
  - path: patch-backend-env.yaml
    target:
      kind: Deployment
      name: backend
