apiVersion: v1
kind: Namespace
metadata:
  name: future-gadget-dev
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: future-gadget-test
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: future-gadget
  labels:
    app.kubernetes.io/managed-by: argocd