apiVersion: v1
kind: Namespace
metadata:
  name: ultimate-web-stack-dev
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: ultimate-web-stack-test
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: ultimate-web-stack
  labels:
    app.kubernetes.io/managed-by: argocd
